default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  host: db

development:
  <<: *default
  database: react-rails-isomorphic_development

test:
  <<: *default
  database: react-rails-isomorphic_test

production:
  <<: *default
  database: react-rails-isomorphic_production
