production: &production
  :url: redis://redis:6379
  :host: redis
  :port: 6379
  :timeout: 1
development: &development
  :url: redis://redis:6379
  :host: redis
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
